feat: whitelist option for no-extraneous-dependencies
un-ts/eslint-plugin-import-x pull request #142
Opened 2024-08-31 14:31 UTC by Zamiell

This PR also includes some typo fixes in "no-extraneous-dependencies.md".

Also note that I had some difficulties in setting up this repo. After a clone, I typed "yarn" to install deps". Then, "npm run build" suceeded, but "npm run test" and "npm run lint" both failed from a completely fresh repo. Is that expected?

2024-08-31 16:53 UTC, SukkaW approved these changes

2024-09-01 04:28 UTC, SukkaW requested changes
Would you mind adding a test case against your changes? Blocking for now.

2024-09-01 11:30 UTC, Zamiell commented
Sure, but note that the existing tests don't even work:

```
$ yarn run test test/rules/no-extraneous-dependencies.spec.ts
yarn run v1.22.19
$ jest test/rules/no-extraneous-dependencies.spec.ts
 FAIL  test/rules/no-extraneous-dependencies.spec.ts
  no-extraneous-dependencies
    valid
      √ import "@org/package" (48 ms)
      √ import foo, { bar } from "@org/package" (4 ms)
      √ require("@org/package") (5 ms)
      √ var foo = require("@org/package") (4 ms)
      √ export { foo } from "@org/package" (3 ms)
      √ export * from "@org/package" (3 ms)
      √ import "esm-package" (6 ms)
      √ import foo, { bar } from "esm-package" (3 ms)
      √ require("esm-package") (3 ms)
      √ var foo = require("esm-package") (3 ms)
      √ export { foo } from "esm-package" (2 ms)
      √ export * from "esm-package" (2 ms)
      √ import "find-up" (3 ms)
      √ import foo, { bar } from "find-up" (2 ms)
      √ require("find-up") (2 ms)
      √ var foo = require("find-up") (2 ms)
      √ export { foo } from "find-up" (2 ms)
      √ export * from "find-up" (2 ms)
      √ import "jquery" (4 ms)
      √ import foo, { bar } from "jquery" (3 ms)
      √ require("jquery") (4 ms)
      √ var foo = require("jquery") (3 ms)
      √ export { foo } from "jquery" (4 ms)
      √ export * from "jquery" (3 ms)
      √ import "lodash.cond" (3 ms)
      √ import foo, { bar } from "lodash.cond" (3 ms)
      √ require("lodash.cond") (3 ms)
      √ var foo = require("lodash.cond") (3 ms)
      √ export { foo } from "lodash.cond" (3 ms)
      √ export * from "lodash.cond" (3 ms)
      √ import "rxjs" (2 ms)
      √ import foo, { bar } from "rxjs" (4 ms)
      √ require("rxjs") (2 ms)
      √ var foo = require("rxjs") (2 ms)
      √ export { foo } from "rxjs" (2 ms)
      √ export * from "rxjs" (1 ms)
      √ import "eslint" (3 ms)
      √ import foo, { bar } from "eslint" (2 ms)
      √ require("eslint") (2 ms)
      √ var foo = require("eslint") (2 ms)
      √ export { foo } from "eslint" (1 ms)
      √ export * from "eslint" (1 ms)
      √ import "glob" (3 ms)
      √ import foo, { bar } from "glob" (2 ms)
      √ require("glob") (1 ms)
      √ var foo = require("glob") (1 ms)
      √ export { foo } from "glob" (2 ms)
      √ export * from "glob" (1 ms)
      √ import "eslint/lib/api" (2 ms)
      √ import "fs" (2 ms)
      √ import "./foo" (2 ms)
      √ import "electron" (1 ms)
      √ import "eslint" (2 ms)
      √ import "importType" (2 ms)
      √ import jest from "jest" (4 ms)
      × import jest from "jest" (10 ms)
      × import jest from "jest" (2 ms)
      √ require(6) (2 ms)
      √ import "doctrine" (2 ms)
      √ import type MyType from "myflowtyped"; (346 ms)
      √
        // @flow
        import typeof TypeScriptModule from 'typescript';
       (6 ms)
      √ import react from "react"; (2 ms)
      √ import leftpad from "left-pad"; (2 ms)
      √ import leftpad from "left-pad"; (1 ms)
      √ import leftpad from "left-pad"; (2 ms)
      √ import leftpad from "left-pad"; (2 ms)
      √ import react from "react"; (1 ms)
      √ import leftpad from "left-pad"; (1 ms)
      √ import rightpad from "right-pad"; (4 ms)
      √ import foo from "@generated/foo" (2 ms)
      √ import foo from "@generated/foo" (2 ms)
      √ import foo from "@generated/foo" (1 ms)
      √ import foo from "@generated/foo" (2 ms)
      √ export function getToken() {} (3 ms)
      √ export class Component extends React.Component {} (2 ms)
      √ export function Component() {} (1 ms)
      √ export const Component = () => {} (2 ms)
      √ import "not-a-dependency" (2 ms)
      √ import "@generated/bar/module" (2 ms)
      √ import "@generated/bar/and/sub/path" (1 ms)
      √ import "rxjs/operators" (1 ms)
      √ import "esm-package/esm-module"; (3 ms)
      √
        import "alias/esm-package/esm-module";
        import 'expose-loader?exposes[]=$&exposes[]=jQuery!jquery';
       (111 ms)
      √ import "@custom-internal-alias/api/service"; (4 ms)
    invalid
      √ import "not-a-dependency" (4 ms)
      √ import "not-a-dependency" (3 ms)
      √ import "not-a-dependency" (2 ms)
      √ import "not-a-dependency" (2 ms)
      √ var donthaveit = require("@org/not-a-dependency") (2 ms)
      √ var donthaveit = require("@org/not-a-dependency/foo") (3 ms)
      √ import "eslint" (1 ms)
      √ import "lodash" (3 ms)
      √ var foo = require("not-a-dependency") (1 ms)
      √ var glob = require("glob") (2 ms)
      √ import jest from "jest" (2 ms)
      √ import jest from "jest" (2 ms)
      √ import jest from "jest" (2 ms)
      √ import jest from "jest" (5 ms)
      √ var eslint = require("lodash") (1 ms)
      √ import "not-a-dependency" (1 ms)
      √ import "bar" (3 ms)
      √ import foo from "foo" (3 ms)
      √ import leftpad from "left-pad"; (2 ms)
      √ import react from "react"; (2 ms)
      √ import react from "react"; (2 ms)
      √ import "react"; (2 ms)
      √ import bar from "@generated/bar" (2 ms)
      √ import foo from "@generated/foo" (2 ms)
      √ import bar from "@generated/bar" (1 ms)
      √ export { foo } from "not-a-dependency"; (2 ms)
      √ export * from "not-a-dependency"; (1 ms)
      √ import jest from "alias/jest"; (5 ms)
      √ import "esm-package-not-in-pkg-json/esm-module"; (2 ms)
      √ import "not-a-dependency" (2 ms)
  TypeScript
    no-extraneous-dependencies
      valid
        √ import type T from "a"; (1 ms)
        √ import type { T } from "a"; export type { T }; (1 ms)
        √ export type { T } from "a"; (1 ms)
      invalid
        √ import T from "a"; (2 ms)
        √ import type T from "a"; (2 ms)
  no-extraneous-dependencies typescript type imports
    valid
      √ import type MyType from "not-a-dependency"; (23 ms)
      √ import type { MyType } from "not-a-dependency"; (4 ms)
      √ import { type MyType } from "not-a-dependency"; (3 ms)
      √ import { type MyType, type OtherType } from "not-a-dependency"; (3 ms)
    invalid
      √ import type { MyType } from "not-a-dependency"; (4 ms)
      √ import type { Foo } from 'not-a-dependency'; (3 ms)
      √ import Foo, { type MyType } from "not-a-dependency"; (4 ms)
      √ import { type MyType, Foo } from "not-a-dependency"; (3 ms)

  ● no-extraneous-dependencies › valid › import jest from "jest"

    assert.strictEqual(received, expected)

    Expected value to strictly be equal to:
      0
    Received:
      1

    Message:
      Should have no errors but had 1: [
      {
        ruleId: '@rule-tester/no-extraneous-dependencies',
        severity: 2,
        message: "'jest' should be listed in the project's dependencies, not devDependencies.",
        line: 1,
        column: 1,
        nodeType: 'ImportDeclaration',
        messageId: 'devDep',
        endLine: 1,
        endColumn: 24
      }
    ]

      at RuleTester.#testValidTemplate (node_modules/@typescript-eslint/rule-tester/src/RuleTester.ts:805:12)
      at Object.<anonymous> (node_modules/@typescript-eslint/rule-tester/src/RuleTester.ts:499:38)

  ● no-extraneous-dependencies › valid › import jest from "jest"

    assert.strictEqual(received, expected)

    Expected value to strictly be equal to:
      0
    Received:
      1

    Message:
      Should have no errors but had 1: [
      {
        ruleId: '@rule-tester/no-extraneous-dependencies',
        severity: 2,
        message: "'jest' should be listed in the project's dependencies, not devDependencies.",
        line: 1,
        column: 1,
        nodeType: 'ImportDeclaration',
        messageId: 'devDep',
        endLine: 1,
        endColumn: 24
      }
    ]

      at RuleTester.#testValidTemplate (node_modules/@typescript-eslint/rule-tester/src/RuleTester.ts:805:12)
      at Object.<anonymous> (node_modules/@typescript-eslint/rule-tester/src/RuleTester.ts:499:38)
```

2024-09-01 11:42 UTC, Zamiell commented
By the way, I think using a set over an array actually reduces perf because of the hashing involved. This stack overflow thread says that for sets with less than 20 elements, it is optimal to use an array instead: https://stackoverflow.com/a/75514478/1062714

2024-09-01 11:52 UTC, Zamiell commented
Test case is added now.

2024-09-04 11:35 UTC, SukkaW approved these changes

2024-09-04 11:35 UTC, merged